### ISSUE TITLE
UCS-001: Upload new datasets

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#1]
## Title 
UCS-001: Upload new datasets

## Description 
The user obtains weather observations from multiple locations.  
He assembles a CSV file per new observation, per location.  
He uploads the CSV file by FTP in order to make the data available.  
The uploaded data is processed by the system and entered into a database.

## Triggers 
The user obtains weather observations.

## Actors 
Mouktar.

## Preconditions 
- UCS-015: The user is authenticated.  
- UCS-003: The HTML pages that host the weather observation information are available.  
- The user has access to a properly configured FTP client.  
- The user has obtained obtained weather observations.  
- The user has assembled the CSV files that will be uploaded.  

## Steps of Execution 
1. Each CSV file is uploaded to the FTP server.

## Success Conditions
The weather observation data will be inserted into the database and are thus available for dissemination.

## Dependent Use Cases
None.

**Comment by rogers492** [comment]
Accepted at the internal demo on 8-Mar-2018.
