### ISSUE TITLE
UCS-019: Maintain an Authoritative WIS Catalogue

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#11]
## Title 
UCS-019: Maintain an Authoritative WIS Catalogue

## Description 
The user navigates to the "Authoritative Dataset Registration" page of the AWISC web application. There fills-in a form providing the following data:
- Dataset name
- Dataset code
- Dataset root URL
- Contact (The user's contact details)
- WMO approval (The WMO permanent representative's contact details)

## Triggers 
- The user wants to make his dataset pages accessible from AWISC.  

## Actors 
Mouktar.

## Preconditions 
- UCS-015: The user is authenticated.
- UCS-003: The HTML pages that host the weather observation information are available.

## Steps of Execution 
1. The user navigates to the "Authoritative Dataset Registration" page of the AWISC web application.  
2. The user provides all necessary information in the displayed form, and submits it.  
3. The system crawls the dataset root page and scans for dataset information.  
4. The system displays the found results for the user to see.  

## Success Conditions
The user registers his authoritative dataset and visually verifies that AWISC crawled his poages successfully.

## Dependent Use Cases
- UCS-020: Dataset page crawling and indexing
- UCS-021: AWISC dataset HTML search page
- UCS-022: AWISC dataset search Web-API
- UCS-023: Search AWISC through Google

**Comment by rogers492** [comment]
Accepted at the internal demo on 8-Mar-2018.
