### ISSUE TITLE
UCS-021: Observation dataset queue discovery and subscription using the AWISC search page

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#12]
## Title 
UCS-021: Observation dataset queue discovery and subscription using the AWISC search page

## Description 
The user visits the AWISC search page. There they perform another search for observation dataset queues in the location of interest. Mouktar's pages are the only results as only he provides authoritative records for this location. When the user clicks the result link, they are redirected to Mouktar's page where they find the resource name required in order to subscribe to the queue.

## Triggers 
The user wishes to subscribe to a weather observation dataset queue.

## Actors 
Mariam.

## Preconditions 
- UCS-003: Mouktar's dataset pages exist
- UCS-020: The dataset pages are already indexed by AWISC

## Steps of Execution 
1. The user uses the AWISC search page to search for weather observation dataset queues in the location of interest, and is presented with search results including only links to Mouktar's pages.  
2. The user clicks on a link from one of Mouktar's pages, and is redirected there.  
3. The user discovers the queue resource name whithin the information provided from Mouktar's page.  
4. The user enters the queue information on his client software and subscribes to notifications.  

## Success Conditions
The user receives notifications from the subscribed queue(s).

**Comment by rogers492** [comment]
Accepted at the internal demo on 8-Mar-2018.
