### ISSUE TITLE
UCS-020: Dataset page crawling and indexing

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#13]
## Title 
UCS-020: Dataset page crawling and indexing

## Description 
The AWISC web application has spawned a process that crawls and indexes registered dataset pages every hour. This process goes through every registered root page, searches for links to other pages, and crawls them in a recursive fashion, searching for specific JSON-LD data (WMO codes). If that data is found, the application updates its search indexes with that information.

## Triggers 
Occurs repeatedly, every hour.

## Actors 
System.

## Preconditions 
- UCS-019: Maintain an Authoritative WIS Catalogue

## Steps of Execution 
1. The AWISC web application loops through every registered dataset root page.
2. The linked pages are examined for WMO codes.
3. The AWISC search indexes are updated based on the discovered WMO codes.

## Success Conditions
The registered dataset pages are searchable from AWISC.

## Dependent Use Cases
- UCS-021: Observation dataset queue discovery and subscription using the AWISC search page

**Comment by rogers492** [comment]
Accepted at the internal demo on 8-Mar-2018.
