### ISSUE TITLE
UCS-023: Search AWISC through Google

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#14]
## Title 
UCS-023: Search AWISC through Google

## Description 
The user visits the Google search page. From there he searches for authoritative weather datasets. Some search results link to AWISC.

## Triggers 
The user wishes to find authoritative weather datasets.

## Actors 
Public user.

## Preconditions 
- The AWISC's site-map has been registered in Google search.

## Steps of Execution 
1. The user visits the Google search page.  
2. The user enters search terms that would match authoritative datasets on AWISC.  
3. Some of the search results link to AWISC.  

## Success Conditions
The user finds AWISC search result by using Google search.

**Comment by rogers492** [comment]
Waiting for Google crawler to re-index.

**Comment by rogers492** [comment]
Demo  today in Geneva.
