### ISSUE TITLE
CBS TECO demo - Check if we can easily drag n drop files into ftp client via browser

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/djibouti#19]
Check if we can easily drag n drop files into ftp client via browser.

**Comment by NMichas** [comment]
You can drag and drop files from your file explorer window into the ftp client. However, most ftp clients include two windows with local and remote filesystems where you can perform the drag & drop from too:

![featured1](https://user-images.githubusercontent.com/2218296/37352731-9390812c-26e6-11e8-8c5d-33f531ad8dcb.jpg)

**Comment by rogers492** [comment]
Demo ready.
