### ISSUE TITLE
UCS-002: Automatic Weather Station quality control

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#3]
## Title 
UCS-002: Automatic Weather Station quality control

## Description 
The user creates a script that will process incoming data from the automatic weather station queue.
This script will search for values that exceed 3 times the Standard Deviation of the mean value for registered observations.
If such deviations are detected, am email is sent to Muktar, prompting him to double-check the incoming data.
Otherwise, the data are placed on the outgoing dissemination queue.

## Triggers 
Data arrives via the Automatic Weather Station queue.

## Actors 
Local Web Application (System).

## Preconditions 
- UCS-016: The automatic weather station queue exists.  
- UCS-013: The outgoing dissemination queue exists.   
- The quality control script exists.  

## Steps of Execution 
1. The weather observation data arrives to Mouktar's local web application via the automatic weather station queue.  
2. The quality control script is executed on the weather observation data.  
3. The weather observation data that are within the accepted range are placed on the outgoing dissemination queue.  
4. The weather observation data that exceed the allowed deviation are temporarily witheld and a notification email is dispatched to Mouktar.  

## Success Conditions
Correct weather observation data are properly disseminated and incorrect weather observation data are validated by Mouktar.  

## Dependent Use Cases
None.

**Comment by rogers492** [comment]
Not required.
