### ISSUE TITLE
UCS-003: Dataset HTML page content management

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#4]
## Title 
UCS-003: Dataset HTML page content management

## Description 
The user navigates to the "Create HTML Content" page in order to create a new web-page for a dataset. Therein, he is presented with a form in which he enters the following information:
- Dataset description: Name, location information, license, file format, etc.
- Google JSON-LD : The desired structured data that will make the page searchable in Google.
- WMO JSON-LD : Dynamic selection of WMO codes (through textual reference, instead of code name) that should be registered in order for the page to be searchable from AWISC.

Upon form submission, a new web-page is automatically created and made available to the public.

## Triggers 
The user wishes to upload/disseminate new weather observations.

## Actors 
Mouktar.

## Preconditions 
- UCS-015: The user is authenticated.  

## Steps of Execution 
1. The user navigates to the "Create HTML Content" page of the local web application, and is presented with a form.  
2. The user fills the required fields with dataset information, as well as JSON-LD structured data, then submits it.  
3. The system automatically generates an HTML page containing the provided information and makes it available to the public.  

## Success Conditions
The new dataset HTML page is made available to the public.  

## Dependent Use Cases
- UCS-004

**Comment by rogers492** [comment]
Accepted at the internal demo on 8-Mar-2018.
