### ISSUE TITLE
UCS-007: Observation dataset queue discovery and subscription using Google search

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#5]
## Title 
UCS-007: Observation dataset queue discovery and subscription using Google search

## Description 
The user uses the Google search page to search for weather observation dataset queues in the location of interest. Among the many search results, there exist some that link to the pages created by Mouktar. When the user clicks such a link, they are redirected to Mouktar's page where they find the resource name required in order to subscribe to the queue.

## Triggers 
The user wishes to subscribe to a weather observation dataset queue.

## Actors 
Mariam.

## Preconditions 
- UCS-003: Mouktar's dataset pages exist

## Steps of Execution 
1. The user uses the Google search page to search for weather observation dataset queues in the location of interest, and is presented with search results, including some linking to Mouktar's pages.  
2. The user clicks on a link from one of Mouktar's pages, and is redirected there.  
3. The user discovers the queue resource name whithin the information provided from Mouktar's page.  
4. The user enters the queue information on his client software and subscribes to notifications.  

## Success Conditions
The user receives notifications from the subscribed queue(s).

**Comment by rogers492** [comment]
Waiting for Google crawler to re-index.

**Comment by rogers492** [comment]
Demo today in Geneva.
