### ISSUE TITLE
UCS-009: Re-transmission of undelivered notifications

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#7]
## Title 
UCS-009: Re-transmission of undelivered notifications

## Description 
Mariam has not connected to her subscribed queues for several days. When her client connects, the queue then will automatically re-transmit all undelivered notifications messages, withing a maximum period of one week.

## Triggers 
The user connects to the queue after a period of absence.

## Actors 
Mariam, RDSH.

## Preconditions 
- UCS-007: The user has already subscribed to the specific queue.  
- The queue in question does have some undelivered messages for Mariam.  

## Steps of Execution 
1. The user connects to the queue after a period of time.  
2. The RDSH queue detects that there are undelivered notifications for that user.  
3. The RDSH queue re-transmits the undelivered notifications, while also transmitting real-time notifications.

## Success Conditions
The user receives undelivered notifications from the subscribed queue(s).

**Comment by rogers492** [comment]
Not required for TECO demo.
