### ISSUE TITLE
UCS-013: Dataset dissemination queue creation

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#8]
## Title 
UCS-013: Dataset queue creation

## Description 
Mouktar asks Omar to create a new queue in order to disseminate notifications for his new dataset. Omar uses the RDSH user interface and provides the required information in order to create a new queue for Mouktar. When all information is entered, the queue is created and becomes available to both Mouktar and potential subscribers.

## Triggers 
Mouktar wants to disseminate notifications when new entries are added to his dataset.  

## Actors 
Mouktar, Omar.

## Preconditions 
- UCS-015: Omar is authenticated.  
- UCS-018: The RDSH is fully functional.  

## Steps of Execution 
1. Omar navigates to the "Create Queue" page of the RDSH user interface.  
2. Omar fills-in the required information in the form.  
3. Omar clicks on the "Create" button, and the queue is successfully deployed.

## Success Conditions
The new queue is successfully deployed.

## Dependent Use Cases
- UCS-014: Dataset dissemination queue monitoring

**Comment by rogers492** [comment]
Accepted at the internal demo on 8-Mar-2018.
