### ISSUE TITLE
UCS-014: Dataset queue monitoring

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/djibouti#9]
## Title 
UCS-014: Dataset queue monitoring

## Description 
Omar wants to access information concerning the status and general usage of the RDSH queues. He uses the RDSH user interface and gets access to data such as the following:
- Number of connected clients  
- All-time maximum number of connected clients  
- Number of disconnecetd clients  
- Bytes sent  
- Bytes received  
- Number of sent messages  
- Number of received messages
- Number of stored messages
- Number of dropped messages
- Number of in-flight messages
- Number of active subscriptions

## Triggers 
The user wants to monitor the dataset queues.  

## Actors 
Omar.

## Preconditions 
- UCS-015: Omar is authenticated.  
- UCS-018: The RDSH is fully functional.  

## Steps of Execution 
1. The user navigates to the "Queue Status" page of the RDSH user interface.  
2. The user views the information presented on the page.  

## Success Conditions
The user views status information concerning the system queues.

**Comment by rogers492** [comment]
Accepted at the internal demo on 8-Mar-2018.
